version: '3'

services:
  kwh-eform-svc:
    container_name: kwh-eform-svc
    image: kwh-eform-svc
    restart: unless-stopped
    ports:
      - 30000:8080
    environment:
      TZ: Asia/Hong_Kong
      SPRING_PROFILES_ACTIVE: dev
