version: '3'

services:
  kcc-spring-boot-svc:
    container_name: kcc-spring-boot-svc
    image: docker-registry-default.cldpaast71.server.ha.org.hk/kccnonc-kcc-dev/kcc-spring-boot-svc
    restart: unless-stopped
    ports:
      - 30000:8080
    environment:
      TZ: Asia/Hong_Kong
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: ${JWT_SECRET}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
