version: '3'

services:
  kwh-its-data-svc:
    container_name: kwh-its-data-svc
    image: kwh-its-data-svc
    restart: unless-stopped
    ports:
      - 30000:8080
    environment:
      TZ: Asia/Hong_Kong
      SPRING_PROFILES_ACTIVE: dev
