name: Development Workflow

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #    - develop
  #    - "feature/**"
  #    - "release/**"
  #    - "hotfix/**"

jobs:
  _Init_:
    name: Init
    runs-on: ${{ vars.RUNS_ON }}
    outputs:
      product: ${{ steps.set-output-defaults.outputs.product }}
      app-name: ${{ github.event.repository.name }}
      image-tag: ${{ steps.generate-image-tag.outputs.image-tag }}
      artifactory: ${{ steps.set-artifactory-variable.outputs.result }}
      repo-type: ${{ steps.set-output-defaults.outputs.repo-type }}
    steps:
      - name: Set variable of artifactory's docker registry
        uses: bluwy/substitute-string-action@v2
        id: set-artifactory-variable
        with:
          _input-text: ${{ vars.ARTIFACTORY_URL }}
          https://: ""
          /artifactory: ""

      - name: Process string case of product
        id: set-LC-product
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ vars.PRODUCT }}

      - name: Generate image tag
        id: generate-image-tag
        run: |
          echo "image-tag=$(Get-Date -Format "yy.M.d.Hmm")" >> $env:GITHUB_OUTPUT

      - name: Process string case of repo type
        id: set-LC-repo-type
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ vars.REPO_TYPE_DEV }}

      - name: Set outputs default values
        id: set-output-defaults
        run: |
          echo "product=${{ steps.set-LC-product.outputs.lowercase }}" >> $env:GITHUB_OUTPUT
          echo "repo-type=${{ steps.set-LC-repo-type.outputs.lowercase }}" >> $env:GITHUB_OUTPUT

  build-container:
    name: Build Container (DEV)
    needs: [_Init_]
    uses: KCC-Info/kcc-workflow-template/.github/workflows/build-container-workflow.yml@main
    with:
      RUNS_ON: ${{ vars.RUNS_ON }}
      ENVIRONMENT: DEV
      PRODUCT: ${{ needs._Init_.outputs.product }}
      APP_NAME: ${{ needs._Init_.outputs.app-name }}
      IMAGE_TAG: ${{ needs._Init_.outputs.image-tag }}
      REACT_DOTENV_FILE: .env.development
      DOCKER_REGISTRY: ${{ needs._Init_.outputs.artifactory }}
      REPO_TYPE: ${{ needs._Init_.outputs.repo-type }}
    secrets:
      CERT_HA_ROOT_CA: ${{ secrets.CERT_HA_ROOT_CA }}
      CERT_HA_TRIAL_ROOT_CA: ${{ secrets.CERT_HA_TRIAL_ROOT_CA }}
      MVN_CONFIG: ${{ secrets.MVN_CONFIG }}
      MVN_SETTINGS: ${{ secrets.MVN_SETTINGS_DEV }}
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER_DEV }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD_DEV }}

  deploy-dev-c1:
    name: Deploy (DEV C1)
    needs: [_Init_, build-container]
    uses: KCC-Info/kcc-workflow-template/.github/workflows/deploy-ecp-workflow.yml@main
    with:
      RUNS_ON: ${{ vars.RUNS_ON }}
      ENVIRONMENT: DEV
      PRODUCT: ${{ needs._Init_.outputs.product }}
      APP_NAME: ${{ needs._Init_.outputs.app-name }}
      IMAGE_TAG: ${{ needs._Init_.outputs.image-tag }}
      DOCKER_REGISTRY: ${{ needs._Init_.outputs.artifactory }}
      REPO_TYPE: ${{ needs._Init_.outputs.repo-type }}
      CLUSTER_URL: ${{ vars.CLUSTER_URL_DEV_C1 }}
      NAMESPACE: ${{ vars.NAMESPACE_DEV }}
    secrets:
      ECP_SA_TOKEN: ${{ secrets.ECP_SA_TOKEN_DEV_C1 }}