name: Development Workflow

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #    - develop

jobs:
  setup:
    name: Setup
    runs-on: ${{ vars.RUNS_ON }}
    outputs:
      APP_NAME: ${{ github.event.repository.name }}
      IMAGE_TAG: ${{ steps.generate-image-tag.outputs.IMAGE_TAG }}
    steps:
      - name: Generate image tag
        id: generate-image-tag
        run: echo "IMAGE_TAG=$(Get-Date -Format "yy.M.d.Hmm")" >> $env:GITHUB_OUTPUT

  build-container:
    name: Build Container (DEV)
    needs: [setup]
    uses: KCC-Info/kcc-workflow-template/.github/workflows/build-container-workflow.yml@main
    with:
      RUNS_ON: ${{ vars.RUNS_ON }}
      ENVIRONMENT: DEV
      APP_NAME: ${{ needs.setup.outputs.APP_NAME }}
      IMAGE_TAG: ${{ needs.setup.outputs.IMAGE_TAG }}
      REACT_DOTENV_FILE: .env.development
      DOCKER_REGISTRY: ${{ vars.ARTIFACTORY_DOCKER_REGISTRY }}
      ARTIFACTORY_REPO_PATH: ${{ vars.ARTIFACTORY_REPO_PATH_DEV }}
    secrets:
      CERT_HA_ROOT_CA: ${{ secrets.CERT_HA_ROOT_CA }}
      MVN_CONFIG: ${{ secrets.MVN_CONFIG }}
      MVN_SETTINGS: ${{ secrets.MVN_SETTINGS_DEV }}
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER_DEV }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD_DEV }}

  deploy-dev-c1:
    name: Deploy (DEV C1)
    needs: [setup, build-container]
    uses: KCC-Info/kcc-workflow-template/.github/workflows/deploy-ecp-workflow.yml@main
    with:
      RUNS_ON: ${{ vars.RUNS_ON }}
      ENVIRONMENT: DEV
      APP_NAME: ${{ needs.setup.outputs.APP_NAME }}
      IMAGE_TAG: ${{ needs.setup.outputs.IMAGE_TAG }}
      DOCKER_REGISTRY: ${{ vars.ARTIFACTORY_DOCKER_REGISTRY }}
      ARTIFACTORY_REPO_PATH: ${{ vars.ARTIFACTORY_REPO_PATH_DEV }}
      CLUSTER_URL: ${{ vars.CLUSTER_URL_DEV_C1 }}
      NAMESPACE: ${{ vars.NAMESPACE_DEV }}
      YAML_CONFIG_FILE: openshift-dev\${{ needs.setup.outputs.APP_NAME }}.yaml
    secrets:
      ECP_SA_TOKEN: ${{ secrets.ECP_SA_TOKEN_DEV_C1 }}