name: Production Workflow

on:
  workflow_dispatch:
  push:
    tags:
      - "**"

jobs:
  _Init_:
    name: Init
    runs-on: ${{ vars.RUNS_ON }}
    outputs:
      product: ${{ steps.set-output-defaults.outputs.product }}
      app-name: ${{ github.event.repository.name }}
      image-tag: ${{ steps.generate-image-tag.outputs.image-tag }}
      artifactory: ${{ steps.set-artifactory-variable.outputs.result }}
      repo-type: ${{ steps.set-output-defaults.outputs.repo-type }}
    steps:
      - name: Set variable of artifactory's docker registry
        uses: bluwy/substitute-string-action@v2
        id: set-artifactory-variable
        with:
          _input-text: ${{ vars.ARTIFACTORY_URL }}
          https://: ""
          /artifactory: ""

      - name: Process string case of product
        id: set-LC-product
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ vars.PRODUCT }}

      - name: Generate image tag
        id: generate-image-tag
        run: |
          echo "image-tag=$(Get-Date -Format "yy.M.d.Hmm")" >> $env:GITHUB_OUTPUT

      - name: Set outputs default values
        id: set-output-defaults
        run: echo "product=${{ steps.set-LC-product.outputs.lowercase }}" >> $env:GITHUB_OUTPUT

  build-container:
    name: Build Container (PRD)
    needs: [_Init_]
    uses: KCC-Info/kcc-workflow-template/.github/workflows/build-container-workflow.yml@main
    with:
      RUNS_ON: ${{ vars.RUNS_ON }}
      ENVIRONMENT: PRD
      PRODUCT: ${{ needs._Init_.outputs.product }}
      APP_NAME: ${{ needs._Init_.outputs.app-name }}
      IMAGE_TAG: ${{ needs._Init_.outputs.image-tag }}
      DOCKER_REGISTRY: ${{ needs._Init_.outputs.artifactory }}
      REPO_TYPE: prd
    secrets:
      CERT_HA_ROOT_CA: ${{ secrets.CERT_HA_ROOT_CA }}
      CERT_HA_TRIAL_ROOT_CA: ${{ secrets.CERT_HA_TRIAL_ROOT_CA }}
      MVN_CONFIG: ${{ secrets.MVN_CONFIG }}
      MVN_SETTINGS: ${{ secrets.MVN_SETTINGS_PRD }}
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER_PRD }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD_PRD }}

  deploy-prd-c1:
    name: Deploy (PRD C1)
    needs: [_Init_, build-container]
    uses: KCC-Info/kcc-workflow-template/.github/workflows/deploy-ecp-workflow.yml@main
    with:
      RUNS_ON: ${{ vars.RUNS_ON }}
      ENVIRONMENT: PRD
      PRODUCT: ${{ needs._Init_.outputs.product }}
      APP_NAME: ${{ needs._Init_.outputs.app-name }}
      IMAGE_TAG: ${{ needs._Init_.outputs.image-tag }}
      DOCKER_REGISTRY: ${{ needs._Init_.outputs.artifactory }}
      REPO_TYPE: prd
      CLUSTER_URL: ${{ vars.CLUSTER_URL_PRD_C1 }}
      NAMESPACE: ${{ vars.NAMESPACE_PRD }}
    secrets:
      ECP_SA_TOKEN: ${{ secrets.ECP_SA_TOKEN_PRD_C1 }}

  deploy-prd-c2:
    name: Deploy (PRD C2)
    needs: [_Init_, build-container]
    uses: KCC-Info/kcc-workflow-template/.github/workflows/deploy-ecp-workflow.yml@main
    with:
      RUNS_ON: ${{ vars.RUNS_ON }}
      ENVIRONMENT: PRD
      PRODUCT: ${{ needs._Init_.outputs.product }}
      APP_NAME: ${{ needs._Init_.outputs.app-name }}
      IMAGE_TAG: ${{ needs._Init_.outputs.image-tag }}
      DOCKER_REGISTRY: ${{ needs._Init_.outputs.artifactory }}
      REPO_TYPE: prd
      CLUSTER_URL: ${{ vars.CLUSTER_URL_PRD_C2 }}
      NAMESPACE: ${{ vars.NAMESPACE_PRD }}
    secrets:
      ECP_SA_TOKEN: ${{ secrets.ECP_SA_TOKEN_PRD_C2 }}